### PR TITLE
Milestone 3: Game logic

### PR DESCRIPTION
**Pull request by arslanbisharat**
The logic from main.rb to classes inside the lib directory and main.rb is now responsible only for user interaction.
Followed the instructions from this-site[https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status:: Require changes☑️
# 👋team,
You have done a good job so far, The game functions almost well. Here are a few improvements we have to make to get this project approved.👨
* [x] After entering the names of players, I think it better to prompt each user what their respective symbols are.
* [x] When the game start and any of the user enters an alphabet ie "a b,c..., etc" the game should not throw an error and just truncate, like below
error_tic
it better to equally treat that selection as a wrong or invalid move.
* [x] Player one or two should not be numbers, isn't a bit weird if player one is called 3 and two 39?? let us keep the names as names. Currently, I can enter numbers as name for either players check below
names
* [x] Again Player names must not accept empty values. It should accept some values. Currently, the game accepts empty values as names. Check below
empty
# That is it, let us make these few tweaks and submit the project for review.👨
#### Happy coding💻
Addo

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team      
#### Great Job so far, but there are a few more things required. 
- [x] Lets fix the linter error.
- [x] The position of X & O on the board is wrongly implemented.

- [x] Player names must not accept empty values as stipulated by previous TSE.


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by Anna-Myzukina** [comment]
# Hi team! :clap: 
### Good job  in Milestone 3 :eyes: 

### Just few changes before it can be approved :100: 
##### Implementation details

As mentioned previously by TSE @kobiyoyo, the position of X & O on the board is wrongly implemented.
tic-tac-toe

* [x] Use attr_readers/attr_writers instead of attr_accessors. You must be aware that by using it they allow writing that property from outside the class. That variable can be set to anything,  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)
screenshot

### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Review by maelfosso — CHANGES_REQUESTED** [review]
# CHanges required 

Hello coders,
Thank you for the improvements done! 
However, there are still some issues

1. That error still persists
Screenshot from 2020-05-15 20-37-45
Please, review your `Board#show` method.

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

**Review by Forison — APPROVED** [review]
## Status:: Approved✔️
# 🙋‍♂️ Team,
You have come a long way 🤗, good job on addressing the issue raised.
## Kindly go ahead and merge the branch and proceed to the next task🚴‍♂️. 
#### bHappy coding
Addo

**Pull request merged**
